"use client";

import Link from "next/link";
import { ArrowRight, Sparkles, Shield, Rocket, Target, Star, Briefcase } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import Image from "next/image";
import { Navbar } from "@/components/layout/Navbar";

export default function LandingPage() {
  const heroImage = PlaceHolderImages.find(img => img.id === 'hero-bg')?.imageUrl || "https://picsum.photos/seed/hero/1920/1080";

  return (
    <div className="min-h-screen">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative h-screen flex items-center justify-center overflow-hidden px-6">
        <div className="absolute inset-0 z-0">
          <Image
            src={heroImage}
            alt="Futuristic background"
            fill
            priority
            className="object-cover opacity-20"
            data-ai-hint="futuristic technology background"
          />
          <div className="absolute inset-0 bg-gradient-to-b from-background via-transparent to-background" />
        </div>

        <div className="relative z-10 max-w-5xl text-center space-y-8 animate-in fade-in slide-in-from-bottom-8 duration-1000">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border-primary/30 text-primary font-bold text-sm tracking-widest uppercase">
            <Sparkles className="w-4 h-4" />
            AI Career Advisor 2026
          </div>
          <h1 className="text-6xl md:text-8xl font-headline font-bold leading-tight tracking-tight">
            Elevate Your <span className="bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">Professional</span> Future.
          </h1>
          <p className="text-xl md:text-2xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Harness the power of Gemini AI to discover your perfect career path, acquire missing skills, and build a personalized roadmap to success.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/dashboard">
              <Button size="lg" className="bg-primary hover:bg-primary/80 text-white px-10 py-8 text-xl rounded-2xl shadow-2xl shadow-primary/30 group">
                Get Started Now
                <ArrowRight className="ml-2 group-hover:translate-x-2 transition-transform" />
              </Button>
            </Link>
            <Link href="/history">
              <Button size="lg" variant="outline" className="glass px-10 py-8 text-xl rounded-2xl border-white/10 hover:bg-white/5">
                View History
              </Button>
            </Link>
          </div>
        </div>

        <div className="absolute bottom-10 left-1/2 -translate-x-1/2 animate-bounce">
          <div className="w-6 h-10 rounded-full border-2 border-white/20 flex justify-center p-2">
            <div className="w-1 h-2 bg-primary rounded-full" />
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-24 max-w-7xl mx-auto px-6">
        <div className="text-center space-y-4 mb-20">
          <h2 className="text-4xl md:text-5xl font-headline font-bold">Intelligent Features</h2>
          <p className="text-muted-foreground text-lg max-w-xl mx-auto">Our platform combines cutting-edge AI with expert career strategies to give you an unfair advantage.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {[
            {
              icon: <Target className="w-8 h-8 text-primary" />,
              title: "Career Profiler",
              desc: "Deep analysis of your skills, interests, and educational background using Gemini Pro."
            },
            {
              icon: <Rocket className="w-8 h-8 text-secondary" />,
              title: "Learning Roadmap",
              desc: "Personalized 6-month growth plan with specific monthly milestones and learning objectives."
            },
            {
              icon: <Shield className="w-8 h-8 text-green-500" />,
              title: "Skill Gap Analysis",
              desc: "Visualized comparison between your current skill set and market demands."
            },
            {
              icon: <Star className="w-8 h-8 text-yellow-500" />,
              title: "Voice-First Support",
              desc: "Describe your goals using voice input and listen to your career reports generated by AI."
            },
            {
              icon: <Sparkles className="w-8 h-8 text-purple-500" />,
              title: "Resume Optimization",
              desc: "Actionable tips and AI-generated tweaks to make your resume stand out to employers."
            },
            {
              icon: <Briefcase className="w-8 h-8 text-blue-500" />,
              title: "Vault Storage",
              desc: "Securely save and track your career evolution over time with our encrypted database vault."
            }
          ].map((f, i) => (
            <div key={i} className="glass p-8 rounded-3xl border-white/5 hover:border-primary/20 transition-all hover:-translate-y-2 group">
              <div className="bg-white/5 w-16 h-16 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-primary/10 transition-colors">
                {f.icon}
              </div>
              <h3 className="text-2xl font-headline font-bold mb-3">{f.title}</h3>
              <p className="text-muted-foreground leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-primary" />
            <span className="font-headline font-bold text-xl">StudyGie AI</span>
          </div>
          <p className="text-muted-foreground text-sm">© 2026 StudyGie AI Career Advisor. Designed for the Vibe Coding Challenge.</p>
          <div className="flex gap-6">
            <Link href="#" className="text-muted-foreground hover:text-primary transition-colors">Twitter</Link>
            <Link href="#" className="text-muted-foreground hover:text-primary transition-colors">GitHub</Link>
            <Link href="#" className="text-muted-foreground hover:text-primary transition-colors">Discord</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
