
"use client";

import { useState } from "react";
import { Volume2, VolumeX, Download, Share2, Award, Zap, Briefcase, TrendingUp, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { GenerateCareerReportOutput } from "@/ai/flows/generate-career-report";
import { readCareerReportAloud } from "@/ai/flows/read-career-report-aloud";
import { LearningRoadmap } from "./LearningRoadmap";
import { SkillGapAnalysis } from "./SkillGapAnalysis";
import { useToast } from "@/hooks/use-toast";

interface ReportDisplayProps {
  report: GenerateCareerReportOutput;
}

export function ReportDisplay({ report }: ReportDisplayProps) {
  const { toast } = useToast();
  const [isPlaying, setIsPlaying] = useState(false);
  const [audio, setAudio] = useState<HTMLAudioElement | null>(null);
  const [isCopied, setIsCopied] = useState(false);

  const generateReportText = () => {
    let text = `STUDYGIE AI CAREER ANALYSIS REPORT\n`;
    text += `==================================\n\n`;
    text += `Match Score: ${report.careerMatchPercentage}%\n\n`;
    
    text += `SUGGESTED CAREER PATHS:\n`;
    report.careerSuggestions.forEach(c => text += `- ${c}\n`);
    text += `\n`;

    text += `RECOMMENDED JOB ROLES:\n`;
    report.topJobRoles.forEach(r => text += `- ${r}\n`);
    text += `\n`;

    text += `SKILL GAP ANALYSIS:\n`;
    text += `Current Skills: ${report.skillGapAnalysis.currentSkills.join(', ')}\n`;
    text += `Missing Skills: ${report.skillGapAnalysis.missingSkills.join(', ')}\n`;
    text += `Improvement Suggestions:\n`;
    report.skillGapAnalysis.improvementSuggestions.forEach(s => text += `- ${s}\n`);
    text += `\n`;

    text += `6-MONTH LEARNING ROADMAP:\n`;
    report.learningRoadmap.forEach(m => {
      text += `[${m.month}]\n`;
      m.activities.forEach(a => text += `  • ${a}\n`);
    });
    text += `\n`;

    text += `RESUME OPTIMIZATION TIPS:\n`;
    report.resumeTips.forEach(t => text += `- ${t}\n`);

    text += `\nGenerated by StudyGie AI - Your Future, Architected.`;
    return text;
  };

  const handleSpeak = async () => {
    if (isPlaying && audio) {
      audio.pause();
      setIsPlaying(false);
      return;
    }

    try {
      setIsPlaying(true);
      const textToRead = `Your top career match is ${report.careerSuggestions[0]}. Your match percentage is ${report.careerMatchPercentage}%. Your recommended job roles include ${report.topJobRoles.join(', ')}.`;
      const { media } = await readCareerReportAloud(textToRead);
      const newAudio = new Audio(media);
      setAudio(newAudio);
      newAudio.play();
      newAudio.onended = () => setIsPlaying(false);
    } catch (error) {
      toast({ variant: "destructive", title: "Audio playback failed" });
      setIsPlaying(false);
    }
  };

  const handleDownload = () => {
    const text = generateReportText();
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "StudyGie_Career_Report.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast({ title: "Report downloaded", description: "Your career roadmap is saved as a text document." });
  };

  const handleShare = async () => {
    const text = generateReportText();
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My StudyGie AI Career Report',
          text: text,
        });
        toast({ title: "Shared successfully" });
      } catch (err) {
        // Fallback to clipboard if share was cancelled or failed
        copyToClipboard(text);
      }
    } else {
      copyToClipboard(text);
    }
  };

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setIsCopied(true);
      toast({ title: "Copied to clipboard", description: "Report text is ready to be shared." });
      setTimeout(() => setIsCopied(false), 2000);
    } catch (err) {
      toast({ variant: "destructive", title: "Share failed", description: "Could not copy text to clipboard." });
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-primary/5 p-6 rounded-2xl border border-primary/20">
        <div>
          <h2 className="text-3xl font-headline font-bold mb-2">Analysis Result</h2>
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="text-primary border-primary">Match Score: {report.careerMatchPercentage}%</Badge>
            <span className="text-muted-foreground text-sm">Generated by StudyGie AI</span>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="icon" className="glass" onClick={handleSpeak} title="Listen to summary">
            {isPlaying ? <VolumeX className="text-primary" /> : <Volume2 className="text-primary" />}
          </Button>
          <Button variant="outline" size="icon" className="glass" onClick={handleDownload} title="Download Document">
            <Download className="w-4 h-4" />
          </Button>
          <Button className="bg-primary text-white" onClick={handleShare}>
            {isCopied ? <Check className="w-4 h-4 mr-2" /> : <Share2 className="w-4 h-4 mr-2" />}
            {isCopied ? "Copied" : "Share Report"}
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {report.careerSuggestions.map((career, i) => (
              <div key={i} className="glass p-5 rounded-2xl border-white/5 hover:border-primary/30 transition-all group cursor-default">
                <div className="flex items-center gap-3 mb-3">
                  <div className="p-2 bg-primary/20 rounded-lg group-hover:scale-110 transition-transform">
                    <Briefcase className="w-5 h-5 text-primary" />
                  </div>
                  <h3 className="font-bold text-lg">{career}</h3>
                </div>
                <div className="text-sm text-muted-foreground">
                  Highly matched with your current background and professional aspirations.
                </div>
              </div>
            ))}
          </div>

          <Tabs defaultValue="roadmap" className="w-full">
            <TabsList className="glass w-full justify-start p-1 h-auto mb-6">
              <TabsTrigger value="roadmap" className="px-6 py-2 rounded-lg data-[state=active]:bg-primary">Roadmap</TabsTrigger>
              <TabsTrigger value="certs" className="px-6 py-2 rounded-lg data-[state=active]:bg-primary">Certifications</TabsTrigger>
              <TabsTrigger value="future" className="px-6 py-2 rounded-lg data-[state=active]:bg-primary">Future Trends</TabsTrigger>
            </TabsList>
            <TabsContent value="roadmap">
              <LearningRoadmap roadmap={report.learningRoadmap} />
            </TabsContent>
            <TabsContent value="certs">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {report.recommendedCertifications.map((cert, i) => (
                  <div key={i} className="glass p-4 rounded-xl flex items-start gap-3">
                    <Award className="w-6 h-6 text-secondary shrink-0" />
                    <div>
                      <div className="font-bold text-secondary">{cert}</div>
                      <div className="text-xs text-muted-foreground">Industry-leading certification to boost your credibility.</div>
                    </div>
                  </div>
                ))}
              </div>
            </TabsContent>
            <TabsContent value="future">
              <div className="space-y-4">
                {report.futureOpportunities.map((opp, i) => (
                  <div key={i} className="glass p-4 rounded-xl flex items-center gap-4">
                    <TrendingUp className="w-8 h-8 text-primary/50" />
                    <p className="text-sm italic text-muted-foreground">"{opp}"</p>
                  </div>
                ))}
              </div>
            </TabsContent>
          </Tabs>
        </div>

        <div className="space-y-6">
          <SkillGapAnalysis analysis={report.skillGapAnalysis} />

          <div className="glass p-6 rounded-2xl border-white/10">
            <h4 className="font-headline font-bold text-lg mb-4 flex items-center gap-2">
              <Zap className="w-5 h-5 text-yellow-500" />
              Resume Optimization
            </h4>
            <ul className="space-y-3">
              {report.resumeTips.map((tip, i) => (
                <li key={i} className="flex gap-3 text-sm text-muted-foreground border-b border-white/5 pb-2 last:border-0">
                  <span className="text-primary font-bold">#</span>
                  {tip}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
